[Rainmeter]
Update=-1

[Variables]
VALORANT_PATH="C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=valorant --launch-patchline=live
CURSEFORGE_PATH="D:\Necessary Stuff\overwolf\OverwolfLauncher.exe" -launchapp cchhcaiapeikjbdbpfplgmpobbcdkdaphclbmkbj -from-startmenu
ANTIGRAVITY_PATH="C:\Users\Arush Mehta\AppData\Local\Programs\Antigravity IDE\Antigravity IDE.exe"
GITHUB_PATH="https://github.com/repos"

[StyleHitbox]
SolidColor=0,0,0,1
; NOTE: If you want to see the hitboxes to adjust them, change the above line to:
; SolidColor=255,0,0,100

; --- COMMANDS ---
[MeasureNetUni]
Measure=Plugin
Plugin=RunCommand
Parameter=powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File "#CURRENTPATH#network_switch.ps1" -Target university

[MeasureNetHotspot]
Measure=Plugin
Plugin=RunCommand
Parameter=powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File "#CURRENTPATH#network_switch.ps1" -Target hotspot

[MeasureCFToggle]
Measure=Plugin
Plugin=RunCommand
Parameter=powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File "#CURRENTPATH#network_switch.ps1" -Target cloudflare

; --- DESKTOP ICONS ---
[MeterHitboxThisPC]
Meter=Image
MeterStyle=StyleHitbox
X=145
Y=22
W=70
H=50
LeftMouseUpAction=["shell:MyComputerFolder"]

[MeterHitboxRecycleBin]
Meter=Image
MeterStyle=StyleHitbox
X=230
Y=22
W=85
H=52
LeftMouseUpAction=["shell:RecycleBinFolder"]

; --- COMMAND CENTER ---
; Base X = 1572, Width = 300

[MeterHitboxNetUni]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=380
W=300
H=25
LeftMouseUpAction=[!CommandMeasure MeasureNetUni "Run"]

[MeterHitboxNetHot]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=410
W=300
H=25
LeftMouseUpAction=[!CommandMeasure MeasureNetHotspot "Run"]

[MeterHitboxNetCF]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=440
W=300
H=25
LeftMouseUpAction=[!CommandMeasure MeasureCFToggle "Run"]

[MeterHitboxAppValorant]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=514
W=300
H=21
LeftMouseUpAction=[#VALORANT_PATH#]

[MeterHitboxAppCurseForge]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=539
W=300
H=21
LeftMouseUpAction=[#CURSEFORGE_PATH#]

[MeterHitboxDevAntigravity]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=600
W=300
H=21
LeftMouseUpAction=["explorer.exe" #ANTIGRAVITY_PATH#]

[MeterHitboxDevTerminal]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=627
W=300
H=21
LeftMouseUpAction=["wt.exe"]

[MeterHitboxDevGithub]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=655
W=300
H=21
LeftMouseUpAction=["#GITHUB_PATH#"]

[MeterHitboxFilesDownloads]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=721
W=300
H=21
LeftMouseUpAction=["C:\Users\%USERNAME%\Downloads"]

[MeterHitboxFilesDocuments]
Meter=Image
MeterStyle=StyleHitbox
X=1572
Y=746
W=300
H=21
LeftMouseUpAction=["C:\Users\%USERNAME%\Documents"]
